/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PosShabuSystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Simon
 */
public class ManageAccount extends javax.swing.JFrame {

    File F = new File("O:\\NetBeans-24\\POS_Shabu_System");
    
    public ManageAccount() {
        initComponents();
    }
    
    void showTable() {
    try {
        //reset Table
        AccountTable.setModel(new DefaultTableModel(null, new String[] {} ) ); 
        
        //Choose location
        BufferedReader BR = new BufferedReader(new FileReader(F+"\\Account.txt"));

        // Read the first line to get the column names
        String columnsLine = BR.readLine();
        String[] columns = columnsLine.split(":");

        // Set the column names to the JTable model
        DefaultTableModel model = (DefaultTableModel) AccountTable.getModel();
        model.setColumnIdentifiers(columns);

        // Read the remaining lines to get the data and add it to the model
        String line;
        while ((line = BR.readLine()) != null) {
            String[] dataRow = line.split(":");
            model.addRow(dataRow);
        }

        // Close the BufferedReader
        BR.close();

    } catch (IOException ex) {
        // Handle the exception
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Pmain = new javax.swing.JPanel();
        Pacc = new javax.swing.JPanel();
        IDtext = new javax.swing.JLabel();
        accidf = new javax.swing.JTextField();
        NAMEtext = new javax.swing.JLabel();
        accnamef = new javax.swing.JTextField();
        USERNAMEtext = new javax.swing.JLabel();
        accusernamef = new javax.swing.JTextField();
        PASSWORDtext = new javax.swing.JLabel();
        accpermissioncb = new javax.swing.JComboBox<>();
        showTableBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        PERMISSIONtext = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AccountTable = new javax.swing.JTable();
        searchf = new javax.swing.JTextField();
        accpasswordf = new javax.swing.JPasswordField();
        resetdataBtn = new javax.swing.JButton();
        addAccBtn = new javax.swing.JButton();
        deletedataBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(157, 33, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("O:\\NetBeans-24\\allPic\\Profile1.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 937, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 100));

        jPanel2.setBackground(new java.awt.Color(217, 213, 212));

        Pmain.setBackground(new java.awt.Color(255, 255, 255));
        Pmain.setForeground(new java.awt.Color(223, 222, 220));

        Pacc.setBackground(new java.awt.Color(255, 255, 255));

        IDtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDtext.setForeground(new java.awt.Color(0, 0, 0));
        IDtext.setText("ID:");

        accidf.setBackground(new java.awt.Color(255, 255, 255));
        accidf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        accidf.setForeground(new java.awt.Color(0, 0, 0));
        accidf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidfActionPerformed(evt);
            }
        });

        NAMEtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NAMEtext.setForeground(new java.awt.Color(0, 0, 0));
        NAMEtext.setText("Name:");

        accnamef.setBackground(new java.awt.Color(255, 255, 255));
        accnamef.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        accnamef.setForeground(new java.awt.Color(0, 0, 0));
        accnamef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnamefActionPerformed(evt);
            }
        });

        USERNAMEtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USERNAMEtext.setForeground(new java.awt.Color(0, 0, 0));
        USERNAMEtext.setText("Username:");

        accusernamef.setBackground(new java.awt.Color(255, 255, 255));
        accusernamef.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        accusernamef.setForeground(new java.awt.Color(0, 0, 0));

        PASSWORDtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PASSWORDtext.setForeground(new java.awt.Color(0, 0, 0));
        PASSWORDtext.setText("Password:");

        accpermissioncb.setBackground(new java.awt.Color(255, 255, 255));
        accpermissioncb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accpermissioncb.setForeground(new java.awt.Color(0, 0, 0));
        accpermissioncb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff", "manager" }));
        accpermissioncb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accpermissioncbActionPerformed(evt);
            }
        });

        showTableBtn.setBackground(new java.awt.Color(204, 204, 204));
        showTableBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showTableBtn.setForeground(new java.awt.Color(0, 0, 0));
        showTableBtn.setText("Show Table");
        showTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTableBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(204, 204, 204));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 0, 0));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        PERMISSIONtext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PERMISSIONtext.setForeground(new java.awt.Color(0, 0, 0));
        PERMISSIONtext.setText("Permission:");

        AccountTable.setBackground(new java.awt.Color(255, 255, 255));
        AccountTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AccountTable.setForeground(new java.awt.Color(0, 0, 0));
        AccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Password", "Permission"
            }
        ));
        AccountTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        AccountTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(AccountTable);

        searchf.setBackground(new java.awt.Color(255, 255, 255));
        searchf.setForeground(new java.awt.Color(0, 0, 0));

        accpasswordf.setBackground(new java.awt.Color(255, 255, 255));
        accpasswordf.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        accpasswordf.setForeground(new java.awt.Color(0, 0, 0));

        resetdataBtn.setBackground(new java.awt.Color(204, 204, 204));
        resetdataBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetdataBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetdataBtn.setText("Reset Data");
        resetdataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetdataBtnActionPerformed(evt);
            }
        });

        addAccBtn.setBackground(new java.awt.Color(204, 204, 204));
        addAccBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addAccBtn.setForeground(new java.awt.Color(0, 0, 0));
        addAccBtn.setText("Add");
        addAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccBtnActionPerformed(evt);
            }
        });

        deletedataBtn1.setBackground(new java.awt.Color(204, 204, 204));
        deletedataBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletedataBtn1.setForeground(new java.awt.Color(0, 0, 0));
        deletedataBtn1.setText("Delete");
        deletedataBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedataBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PaccLayout = new javax.swing.GroupLayout(Pacc);
        Pacc.setLayout(PaccLayout);
        PaccLayout.setHorizontalGroup(
            PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaccLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NAMEtext)
                    .addComponent(IDtext)
                    .addComponent(USERNAMEtext)
                    .addComponent(PASSWORDtext)
                    .addComponent(PERMISSIONtext))
                .addGap(18, 18, 18)
                .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accusernamef)
                    .addComponent(accnamef)
                    .addComponent(accidf)
                    .addComponent(accpermissioncb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accpasswordf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaccLayout.createSequentialGroup()
                        .addComponent(searchf, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetdataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletedataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        PaccLayout.setVerticalGroup(
            PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaccLayout.createSequentialGroup()
                .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaccLayout.createSequentialGroup()
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDtext)
                            .addComponent(accidf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAMEtext)
                            .addComponent(accnamef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(USERNAMEtext)
                            .addComponent(accusernamef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accpasswordf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PASSWORDtext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(accpermissioncb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PERMISSIONtext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn)
                            .addComponent(searchf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(PaccLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(showTableBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addAccBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletedataBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetdataBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout PmainLayout = new javax.swing.GroupLayout(Pmain);
        Pmain.setLayout(PmainLayout);
        PmainLayout.setHorizontalGroup(
            PmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PmainLayout.createSequentialGroup()
                .addComponent(Pacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PmainLayout.setVerticalGroup(
            PmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pacc, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1280, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon("O:\\NetBeans-24\\allPic\\bg2.png")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 750));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 750));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 750));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);  
        new ManagerMenu("M001","Fern").setVisible(true);  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void accidfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accidfActionPerformed

    private void accpermissioncbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accpermissioncbActionPerformed

    }//GEN-LAST:event_accpermissioncbActionPerformed

    private void addAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccBtnActionPerformed
        Manager manager = new Manager();
        User user = new User();
        user.createDir();
        user.readFile();
        manager.countLines();
        manager.regisUser(accidf.getText(),accnamef.getText(),accusernamef.getText(),accpasswordf.getText(),accpermissioncb.getSelectedItem().toString()); //accpermissionf.getText()
        showTable();
    }//GEN-LAST:event_addAccBtnActionPerformed

    private void showTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTableBtnActionPerformed
        showTable();
    }//GEN-LAST:event_showTableBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        DefaultTableModel obj=(DefaultTableModel) AccountTable.getModel();
        TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
        AccountTable.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(searchf.getText()));
    }//GEN-LAST:event_searchBtnActionPerformed

    private void resetdataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetdataBtnActionPerformed
        Manager manager = new Manager();
        int response = JOptionPane.showConfirmDialog(this,"Do you want to reset all data ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
        manager.resetTable();
        showTable();
        }else{
        System.out.println("NO OR EXIT");
        }
    }//GEN-LAST:event_resetdataBtnActionPerformed

    private void accnamefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnamefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnamefActionPerformed

    private void deletedataBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedataBtn1ActionPerformed
        int selectedRow = AccountTable.getSelectedRow();  
    if (selectedRow != -1) { 
        int response = JOptionPane.showConfirmDialog(this,
                "Do you want to delete the selected row?", 
                "Confirm Delete", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) AccountTable.getModel();
            model.removeRow(selectedRow);

            deleteRowFromFile(selectedRow);

            System.out.println("Row Deleted");
        } else {
            System.out.println("Delete Cancelled");
        }
    } else {
        JOptionPane.showMessageDialog(this, "No row selected", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void deleteRowFromFile(int rowIndex) {
    try {
        BufferedReader BR = new BufferedReader(new FileReader(F+"\\Account.txt"));
        ArrayList<String> lines = new ArrayList<>();
        String line;

        while ((line = BR.readLine()) != null) {
            lines.add(line);
        }
        BR.close();

        if (rowIndex >= 0 && rowIndex < lines.size()) {
            lines.remove(rowIndex);
        }
        BufferedWriter writer = new BufferedWriter(new FileWriter(F+"\\Account.txt"));
        for (String row : lines) {
            writer.write(row);
            writer.newLine();
        }
        writer.close();
    } catch (IOException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_deletedataBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu("M001","Fern").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AccountTable;
    private javax.swing.JLabel IDtext;
    private javax.swing.JLabel NAMEtext;
    private javax.swing.JLabel PASSWORDtext;
    private javax.swing.JLabel PERMISSIONtext;
    private javax.swing.JPanel Pacc;
    private javax.swing.JPanel Pmain;
    private javax.swing.JLabel USERNAMEtext;
    private javax.swing.JTextField accidf;
    private javax.swing.JTextField accnamef;
    private javax.swing.JPasswordField accpasswordf;
    private javax.swing.JComboBox<String> accpermissioncb;
    private javax.swing.JTextField accusernamef;
    private javax.swing.JButton addAccBtn;
    private javax.swing.JButton deletedataBtn1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetdataBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchf;
    private javax.swing.JButton showTableBtn;
    // End of variables declaration//GEN-END:variables
}
